name: ubb
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  animate_do: ^3.1.2
  bloc: ^8.1.2
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_map: ^6.0.1
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^10.6.0
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  google_polyline_algorithm: ^3.1.0
  http: ^1.1.0
  intl: ^0.18.1 
  latlong2: ^0.9.0
  permission_handler: ^11.0.1
  provider: ^6.0.5
  card_swiper: ^3.0.1
  path_provider: ^2.1.1
  firebase_database: ^10.3.2
  curved_navigation_bar: ^1.0.3
  firebase_core: ^2.27.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  json_annotation: ^4.8.0


dev_dependencies:
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.0
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/weather_img/
