name: ubb
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  animate_do: ^3.0.2
  bloc: ^8.1.2
  dio: ^5.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_map: ^5.0.0
  flutter_secure_storage: ^8.0.0
  font_awesome_flutter: ^10.4.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.8
  google_polyline_algorithm: ^3.1.0
  http: ^1.0.0
  intl: ^0.18.1 
  latlong2: ^0.9.0
  permission_handler: ^10.2.0
  provider: ^6.0.5
  card_swiper: ^3.0.1


dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/
